import Foundation

struct UserLogsAnalyzer: CleanupAnalyzer {
    let key = "user_logs"
    let title = "User Logs"
    let description = "Old log files from ~/Library/Logs"
    let isSafeByDefault = true

    func analyze(excludedPrefixes: [String]) async -> CleanupCategoryResult {
        let root = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Logs")
        let items = CleanupFileEnumerator.collectFiles(in: root, olderThanDays: 14, excludedPrefixes: excludedPrefixes)
        return CleanupCategoryResult(key: key, title: title, description: description, isSafeByDefault: isSafeByDefault, riskLevel: .low, recommendationReason: "Old logs are usually safe to remove and regenerated by apps.", items: items)
    }
}

struct UserCachesAnalyzer: CleanupAnalyzer {
    let key = "user_caches"
    let title = "User Caches"
    let description = "Cache files from ~/Library/Caches"
    let isSafeByDefault = true

    func analyze(excludedPrefixes: [String]) async -> CleanupCategoryResult {
        let root = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Caches")
        let items = CleanupFileEnumerator.collectFiles(in: root, olderThanDays: 7, excludedPrefixes: excludedPrefixes)
        return CleanupCategoryResult(key: key, title: title, description: description, isSafeByDefault: isSafeByDefault, riskLevel: .low, recommendationReason: "Cache cleanup usually frees space with low functional risk.", items: items)
    }
}

struct OldDownloadsAnalyzer: CleanupAnalyzer {
    let key = "old_downloads"
    let title = "Old Downloads"
    let description = "Files in ~/Downloads older than 30 days"
    let isSafeByDefault = false

    func analyze(excludedPrefixes: [String]) async -> CleanupCategoryResult {
        let root = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Downloads")
        let items = CleanupFileEnumerator.collectFiles(in: root, olderThanDays: 30, excludedPrefixes: excludedPrefixes)
        return CleanupCategoryResult(key: key, title: title, description: description, isSafeByDefault: isSafeByDefault, riskLevel: .medium, recommendationReason: "Downloads can contain user data; review before cleaning.", items: items)
    }
}

struct XcodeDerivedDataAnalyzer: CleanupAnalyzer {
    let key = "xcode_derived_data"
    let title = "Xcode DerivedData"
    let description = "Build artifacts from ~/Library/Developer/Xcode/DerivedData"
    let isSafeByDefault = true

    func analyze(excludedPrefixes: [String]) async -> CleanupCategoryResult {
        let root = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Developer/Xcode/DerivedData")
        let items = CleanupFileEnumerator.collectFiles(in: root, olderThanDays: 2, excludedPrefixes: excludedPrefixes)
        return CleanupCategoryResult(key: key, title: title, description: description, isSafeByDefault: isSafeByDefault, riskLevel: .low, recommendationReason: "DerivedData is reproducible build output.", items: items)
    }
}

struct IOSBackupsAnalyzer: CleanupAnalyzer {
    let key = "ios_backups"
    let title = "iOS Backups"
    let description = "Local iPhone/iPad backups"
    let isSafeByDefault = false

    func analyze(excludedPrefixes: [String]) async -> CleanupCategoryResult {
        let root = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Application Support/MobileSync/Backup")
        let items = CleanupFileEnumerator.collectFiles(in: root, olderThanDays: 14, excludedPrefixes: excludedPrefixes)
        return CleanupCategoryResult(key: key, title: title, description: description, isSafeByDefault: isSafeByDefault, riskLevel: .high, recommendationReason: "Backups may be critical for restore workflows.", items: items)
    }
}

struct MailDownloadsAnalyzer: CleanupAnalyzer {
    let key = "mail_downloads"
    let title = "Mail Downloads"
    let description = "Attachments saved by Apple Mail"
    let isSafeByDefault = false

    func analyze(excludedPrefixes: [String]) async -> CleanupCategoryResult {
        let root = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Containers/com.apple.mail/Data/Library/Mail Downloads")
        let items = CleanupFileEnumerator.collectFiles(in: root, olderThanDays: 30, excludedPrefixes: excludedPrefixes)
        return CleanupCategoryResult(key: key, title: title, description: description, isSafeByDefault: isSafeByDefault, riskLevel: .medium, recommendationReason: "Attachments may include user documents; inspect before delete.", items: items)
    }
}

struct LanguageFilesAnalyzer: CleanupAnalyzer {
    let key = "language_files"
    let title = "Language Files"
    let description = "Localized resource files in user Library"
    let isSafeByDefault = false

    func analyze(excludedPrefixes: [String]) async -> CleanupCategoryResult {
        let root = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library")
        let items = CleanupFileEnumerator.collectLanguageFiles(in: root, excludedPrefixes: excludedPrefixes)
        return CleanupCategoryResult(key: key, title: title, description: description, isSafeByDefault: isSafeByDefault, riskLevel: .medium, recommendationReason: "Removing language resources can break localization for some apps.", items: items)
    }
}

struct OrphanPreferencesAnalyzer: CleanupAnalyzer {
    let key = "orphan_preferences"
    let title = "Orphan Preferences"
    let description = "Preference files for apps not found in /Applications"
    let isSafeByDefault = true

    func analyze(excludedPrefixes: [String]) async -> CleanupCategoryResult {
        let root = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Preferences")
        let items = CleanupFileEnumerator.collectOrphanPreferenceFiles(in: root, excludedPrefixes: excludedPrefixes)
        return CleanupCategoryResult(key: key, title: title, description: description, isSafeByDefault: isSafeByDefault, riskLevel: .low, recommendationReason: "Preference remnants for removed apps are typically safe to clean.", items: items)
    }
}

enum CleanupFileEnumerator {
    static func collectFiles(in root: URL, olderThanDays days: Int, excludedPrefixes: [String]) -> [CleanupItem] {
        let fm = FileManager.default
        guard fm.fileExists(atPath: root.path) else { return [] }

        let keys: Set<URLResourceKey> = [.isDirectoryKey, .contentModificationDateKey, .fileSizeKey]
        guard let enumerator = fm.enumerator(at: root, includingPropertiesForKeys: Array(keys), options: [.skipsHiddenFiles]) else {
            return []
        }

        let cutoff = Calendar.current.date(byAdding: .day, value: -days, to: Date()) ?? .distantPast
        var result: [CleanupItem] = []

        for case let fileURL as URL in enumerator {
            let path = fileURL.path
            if excludedPrefixes.contains(where: { path == $0 || path.hasPrefix($0 + "/") }) {
                continue
            }
            guard let values = try? fileURL.resourceValues(forKeys: keys), values.isDirectory != true else { continue }
            guard let modified = values.contentModificationDate, modified < cutoff else { continue }
            let size = Int64(values.fileSize ?? 0)
            result.append(CleanupItem(url: fileURL, sizeInBytes: size))
        }

        return result.sorted { $0.sizeInBytes > $1.sizeInBytes }
    }

    static func collectLanguageFiles(in root: URL, excludedPrefixes: [String]) -> [CleanupItem] {
        let fm = FileManager.default
        guard fm.fileExists(atPath: root.path),
              let enumerator = fm.enumerator(at: root, includingPropertiesForKeys: [.isDirectoryKey, .fileSizeKey], options: [.skipsHiddenFiles]) else {
            return []
        }

        var result: [CleanupItem] = []
        for case let fileURL as URL in enumerator {
            let path = fileURL.path
            if excludedPrefixes.contains(where: { path == $0 || path.hasPrefix($0 + "/") }) { continue }
            guard path.contains(".lproj/") else { continue }
            guard let values = try? fileURL.resourceValues(forKeys: [.isDirectoryKey, .fileSizeKey]), values.isDirectory != true else { continue }
            result.append(CleanupItem(url: fileURL, sizeInBytes: Int64(values.fileSize ?? 0)))
        }
        return result.sorted { $0.sizeInBytes > $1.sizeInBytes }
    }

    static func collectOrphanPreferenceFiles(in root: URL, excludedPrefixes: [String]) -> [CleanupItem] {
        let fm = FileManager.default
        guard fm.fileExists(atPath: root.path),
              let enumerator = fm.enumerator(at: root, includingPropertiesForKeys: [.isDirectoryKey, .fileSizeKey], options: [.skipsHiddenFiles]) else {
            return []
        }

        let installed = installedBundleIDs()
        var result: [CleanupItem] = []
        for case let fileURL as URL in enumerator {
            let path = fileURL.path
            if excludedPrefixes.contains(where: { path == $0 || path.hasPrefix($0 + "/") }) { continue }
            guard fileURL.pathExtension == "plist" else { continue }
            guard let values = try? fileURL.resourceValues(forKeys: [.isDirectoryKey, .fileSizeKey]), values.isDirectory != true else { continue }
            let bundleID = fileURL.deletingPathExtension().lastPathComponent
            guard !bundleID.isEmpty, !installed.contains(bundleID) else { continue }
            result.append(CleanupItem(url: fileURL, sizeInBytes: Int64(values.fileSize ?? 0)))
        }
        return result.sorted { $0.sizeInBytes > $1.sizeInBytes }
    }

    private static func installedBundleIDs() -> Set<String> {
        guard let apps = try? FileManager.default.contentsOfDirectory(
            at: URL(fileURLWithPath: "/Applications"),
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        ) else { return [] }

        var ids = Set<String>()
        for appURL in apps where appURL.pathExtension == "app" {
            if let bundle = Bundle(url: appURL), let id = bundle.bundleIdentifier {
                ids.insert(id)
            }
        }
        return ids
    }
}
